#!/usr/bin/env python3
"""
install_localhost.py - install and configure a complete local WaSQL stack.

Installs (or reuses) Apache, PHP and MySQL on Windows, Linux or macOS, wires
them together for WaSQL, creates the WaSQL database/user, writes config.xml, and
optionally runs the WaSQL setup wizard so you end up with a working site at
http://localhost/ and the admin interface at http://localhost/php/admin.php
(default login admin/admin).

Design goals
  * hands off - every question is asked up front, then it runs unattended.
  * -y / --yes runs with defaults and asks nothing at all.
  * idempotent - safe to re-run; generated blocks are sentinel-marked and
    existing files are backed up before being touched.
  * never clobbers an existing config.xml (it reads the db settings out of it
    instead, unless you pass --force-config).

Typical use
  Windows (from an *elevated* PowerShell / cmd):
      python install_localhost.py
  Linux / macOS:
      python3 install_localhost.py          # re-execs itself under sudo
  Fully unattended:
      python3 install_localhost.py --yes --sample wacss

Run with --help for all options, or --check to only verify an existing install.
"""

from __future__ import annotations

import argparse
import ctypes
import glob
import json
import os
import platform
import re
import shutil
import socket
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Optional, Sequence

# ---------------------------------------------------------------------------
# defaults
# ---------------------------------------------------------------------------

DEFAULT_DB_NAME = "wasql_sample"
DEFAULT_DB_USER = "wasql_dbuser"
DEFAULT_DB_PASS = "wasql_dbpass"
DEFAULT_PORT = 80
DEFAULT_SAMPLE = "wacss"          # php/schema/templates/*.zip
SAMPLE_CHOICES = ("wacss", "bulma", "bootstrap", "blank", "none")

SENTINEL_BEGIN = "### BEGIN WaSQL (generated by install_localhost.py) ###"
SENTINEL_END = "### END WaSQL ###"

# php extensions WaSQL cannot run without (index.php bails out on these)
REQUIRED_EXTS = ("mysqli", "curl", "mbstring", "simplexml", "zip", "json",
                 "openssl", "fileinfo")
# nice to have - warn only
RECOMMENDED_EXTS = ("gd", "intl", "exif", "pdo_mysql", "soap", "ldap",
                    "sqlite3", "bcmath", "sockets", "zlib", "iconv", "gettext")

# php.ini settings WaSQL likes (applied everywhere)
PHP_INI_SETTINGS = {
    "memory_limit": "512M",
    "post_max_size": "128M",
    "upload_max_filesize": "120M",
    "max_execution_time": "600",
    "max_input_time": "600",
    "max_input_vars": "10000",
    "default_socket_timeout": "600",
    "display_errors": "Off",
    "log_errors": "On",
    "date.timezone": "America/Denver",
    "mysqli.reconnect": "On",
}

# windows: extension=... lines to enable in php.ini when the dll is present
WIN_EXTENSIONS = ("bz2", "curl", "exif", "fileinfo", "gd", "gettext", "intl",
                  "ldap", "mbstring", "mysqli", "openssl", "pdo_mysql",
                  "pdo_sqlite", "soap", "sockets", "sodium", "sqlite3", "xsl",
                  "zip")

# apache modules that must be active for WaSQL's rewrite based routing
APACHE_MODULES = ("rewrite_module", "alias_module", "dir_module",
                  "mime_module", "authz_core_module", "authz_host_module",
                  "setenvif_module", "headers_module", "expires_module",
                  "filter_module", "deflate_module")

WIN_PHP_RELEASES_URL = "https://windows.php.net/downloads/releases/"
CHOCO_INSTALL_PS = (
    "Set-ExecutionPolicy Bypass -Scope Process -Force; "
    "[System.Net.ServicePointManager]::SecurityProtocol = 3072; "
    "iex ((New-Object System.Net.WebClient)."
    "DownloadString('https://community.chocolatey.org/install.ps1'))"
)
BREW_INSTALL_URL = ("https://raw.githubusercontent.com/Homebrew/install/"
                    "HEAD/install.sh")

IS_WIN = sys.platform.startswith("win")
IS_MAC = sys.platform == "darwin"
IS_LINUX = sys.platform.startswith("linux")

VERBOSE = False
DRY_RUN = False
_WARNINGS: list[str] = []


# ---------------------------------------------------------------------------
# console output
# ---------------------------------------------------------------------------

class C:
    """ANSI colors (disabled when output is not a tty)."""
    BOLD = "\033[1m"
    DIM = "\033[2m"
    RED = "\033[31m"
    GREEN = "\033[32m"
    YELLOW = "\033[33m"
    BLUE = "\033[36m"
    OFF = "\033[0m"

    @classmethod
    def disable(cls):
        for k in ("BOLD", "DIM", "RED", "GREEN", "YELLOW", "BLUE", "OFF"):
            setattr(cls, k, "")


def _init_console():
    if not sys.stdout.isatty() or os.environ.get("NO_COLOR"):
        C.disable()
        return
    if IS_WIN:  # enable VT sequences on legacy consoles
        try:
            k = ctypes.windll.kernel32
            k.SetConsoleMode(k.GetStdHandle(-11), 7)
        except Exception:
            C.disable()


_step_no = 0


def step(msg: str):
    global _step_no
    _step_no += 1
    print(f"\n{C.BOLD}{C.BLUE}[{_step_no}] {msg}{C.OFF}")


def info(msg: str):
    print(f"    {msg}")


def ok(msg: str):
    print(f"    {C.GREEN}OK{C.OFF}  {msg}")


def warn(msg: str):
    _WARNINGS.append(msg)
    print(f"    {C.YELLOW}WARN{C.OFF} {msg}")


def debug(msg: str):
    if VERBOSE:
        print(f"    {C.DIM}{msg}{C.OFF}")


def die(msg: str, code: int = 1):
    print(f"\n{C.RED}{C.BOLD}ERROR{C.OFF} {msg}\n", file=sys.stderr)
    sys.exit(code)


# ---------------------------------------------------------------------------
# process helpers
# ---------------------------------------------------------------------------

@dataclass
class Result:
    code: int
    out: str
    err: str

    @property
    def good(self) -> bool:
        return self.code == 0

    @property
    def text(self) -> str:
        return (self.out + "\n" + self.err).strip()


def run(cmd: Sequence[str] | str, check: bool = False, timeout: int = 1800,
        env: Optional[dict] = None, cwd: Optional[str | Path] = None,
        stdin_text: Optional[str] = None, quiet: bool = False,
        allow_dry: bool = True) -> Result:
    """Run a command and capture output. Never raises unless check=True."""
    shell = isinstance(cmd, str)
    shown = cmd if shell else " ".join(str(c) for c in cmd)
    if DRY_RUN and allow_dry:
        info(f"{C.DIM}[dry-run] {shown}{C.OFF}")
        return Result(0, "", "")
    debug(f"$ {shown}")
    full_env = dict(os.environ)
    if env:
        full_env.update(env)
    try:
        p = subprocess.run(
            cmd if shell else [str(c) for c in cmd],
            shell=shell, capture_output=True, text=True, timeout=timeout,
            env=full_env, cwd=str(cwd) if cwd else None, input=stdin_text,
            errors="replace",
        )
        res = Result(p.returncode, (p.stdout or "").strip(), (p.stderr or "").strip())
    except FileNotFoundError as e:
        res = Result(127, "", str(e))
    except subprocess.TimeoutExpired:
        res = Result(124, "", f"timed out after {timeout}s")
    if VERBOSE and res.text:
        for line in res.text.splitlines()[:40]:
            debug(f"| {line}")
    if not res.good and not quiet:
        debug(f"exit {res.code}: {shown}")
    if check and not res.good:
        die(f"command failed ({res.code}): {shown}\n{res.text}")
    return res


def powershell(script: str, check: bool = False, timeout: int = 1800,
               allow_dry: bool = True) -> Result:
    return run(["powershell.exe", "-NoProfile", "-NonInteractive",
                "-ExecutionPolicy", "Bypass", "-Command", script],
               check=check, timeout=timeout, allow_dry=allow_dry)


def which(*names: str) -> Optional[Path]:
    for n in names:
        p = shutil.which(n)
        if p:
            return Path(p)
    return None


def first_existing(*candidates: str | Path | None) -> Optional[Path]:
    for c in candidates:
        if not c:
            continue
        for hit in sorted(glob.glob(str(c)), reverse=True):
            p = Path(hit)
            if p.exists():
                return p
    return None


def port_in_use(port: int, host: str = "127.0.0.1") -> bool:
    with socket.socket() as s:
        s.settimeout(1.0)
        return s.connect_ex((host, port)) == 0


# ---------------------------------------------------------------------------
# file helpers
# ---------------------------------------------------------------------------

def backup(path: Path) -> Optional[Path]:
    """Copy path to path.wasql-bak (once) so the original is recoverable."""
    if not path.is_file():
        return None
    bak = path.with_suffix(path.suffix + ".wasql-bak")
    if not bak.exists() and not DRY_RUN:
        shutil.copy2(path, bak)
        debug(f"backed up {path} -> {bak.name}")
    return bak


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def write_text(path: Path, text: str, mode: Optional[int] = None):
    """Write text with LF endings (a stray CR breaks apache/my.cnf parsing)."""
    if DRY_RUN:
        info(f"{C.DIM}[dry-run] write {path} ({len(text)} bytes){C.OFF}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    if mode is not None and not IS_WIN:
        try:
            os.chmod(path, mode)
        except OSError as e:
            debug(f"chmod {path}: {e}")


def replace_block(text: str, block: str) -> str:
    """Insert or replace the sentinel-delimited WaSQL block in a config file."""
    payload = f"{SENTINEL_BEGIN}\n{block.strip()}\n{SENTINEL_END}\n"
    pattern = re.compile(re.escape(SENTINEL_BEGIN) + r".*?" +
                         re.escape(SENTINEL_END) + r"\n?", re.S)
    if pattern.search(text):
        return pattern.sub(payload, text)
    if text and not text.endswith("\n"):
        text += "\n"
    return text + "\n" + payload


def ensure_dir(path: Path, writable: bool = False, owner: Optional[str] = None):
    if DRY_RUN:
        info(f"{C.DIM}[dry-run] mkdir {path}{C.OFF}")
        return
    path.mkdir(parents=True, exist_ok=True)
    if writable and not IS_WIN:
        try:
            os.chmod(path, 0o777)
        except OSError as e:
            debug(f"chmod 777 {path}: {e}")
        if owner:
            run(["chown", "-R", f"{owner}:{owner}", str(path)], quiet=True)


def ensure_traversable(path: Path):
    """Give the web server o+x on every parent dir so it can reach the repo."""
    if IS_WIN:
        return
    p = path.resolve()
    parents = list(p.parents)[:-1] + [p]
    for d in parents:
        try:
            mode = d.stat().st_mode & 0o777
        except OSError:
            continue
        if not mode & 0o001:
            debug(f"chmod o+x {d}")
            if not DRY_RUN:
                try:
                    os.chmod(d, mode | 0o001)
                except OSError as e:
                    warn(f"could not chmod o+x {d} ({e}); apache may get 403s")


def download(url: str, dest: Path, label: str = "") -> Path:
    if DRY_RUN:
        info(f"{C.DIM}[dry-run] download {url}{C.OFF}")
        return dest
    info(f"downloading {label or url}")
    req = urllib.request.Request(url, headers={
        "User-Agent": "Mozilla/5.0 (compatible; wasql-installer)"})
    dest.parent.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(req, timeout=180) as resp, open(dest, "wb") as fh:
        total = int(resp.headers.get("Content-Length") or 0)
        done = 0
        while True:
            chunk = resp.read(262144)
            if not chunk:
                break
            fh.write(chunk)
            done += len(chunk)
            if total and sys.stdout.isatty():
                pct = done * 100 // total
                print(f"\r    {done//1048576}/{total//1048576} MB ({pct}%)",
                      end="", flush=True)
    if sys.stdout.isatty() and total:
        print()
    return dest


def http_get(url: str, timeout: int = 30) -> tuple[int, str]:
    req = urllib.request.Request(url, headers={"User-Agent": "wasql-installer"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.status, r.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode("utf-8", "replace")
    except Exception as e:
        return 0, str(e)


# ---------------------------------------------------------------------------
# privileges
# ---------------------------------------------------------------------------

def is_admin() -> bool:
    if IS_WIN:
        try:
            return bool(ctypes.windll.shell32.IsUserAnAdmin())
        except Exception:
            return False
    return os.geteuid() == 0


def require_privileges(argv: list[str]):
    """Windows: demand an elevated shell. POSIX: re-exec through sudo."""
    if is_admin():
        return
    if IS_WIN:
        die("this installer must run elevated.\n"
            "  Right-click 'Windows PowerShell' (or Terminal) -> Run as "
            "administrator, then re-run:\n"
            f"      python {' '.join([Path(sys.argv[0]).name] + argv)}")
    sudo = which("sudo")
    if not sudo:
        die("root privileges are required and sudo was not found. "
            "Re-run this script as root.")
    print(f"{C.YELLOW}Re-running under sudo (you may be asked for your "
          f"password)...{C.OFF}")
    cmd = [str(sudo), "-E", sys.executable, os.path.abspath(sys.argv[0])] + argv
    os.execv(str(sudo), cmd)  # replaces this process


def invoking_user() -> Optional[str]:
    """The human behind a sudo invocation (needed for Homebrew)."""
    u = os.environ.get("SUDO_USER")
    if u and u != "root":
        return u
    return None


# ---------------------------------------------------------------------------
# settings + questions
# ---------------------------------------------------------------------------

@dataclass
class Settings:
    wasql: Path
    docroot: Path
    port: int = DEFAULT_PORT
    db_name: str = DEFAULT_DB_NAME
    db_user: str = DEFAULT_DB_USER
    db_pass: str = DEFAULT_DB_PASS
    db_host: str = "localhost"
    mysql_root_pass: str = ""          # "" = leave whatever is there
    install_packages: bool = True
    sample: str = DEFAULT_SAMPLE
    relax_sql_mode: bool = True
    force_config: bool = False
    php_version: str = ""              # windows only, e.g. "8.4"
    timezone: str = PHP_INI_SETTINGS["date.timezone"]


def ask(prompt: str, default: str, assume_yes: bool,
        choices: Optional[Iterable[str]] = None, secret: bool = False) -> str:
    if assume_yes:
        return default
    shown = f" [{default}]" if default != "" else " []"
    if choices:
        shown = f" ({'/'.join(choices)})" + shown
    while True:
        try:
            val = input(f"  {prompt}{shown}: ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            die("aborted")
        if not val:
            val = default
        if choices and val.lower() not in [c.lower() for c in choices]:
            print(f"    please answer one of: {', '.join(choices)}")
            continue
        return val


def ask_bool(prompt: str, default: bool, assume_yes: bool) -> bool:
    d = "y" if default else "n"
    return ask(prompt, d, assume_yes, choices=("y", "n")).lower().startswith("y")


def read_existing_config(cfg: Path) -> dict:
    """Pull dbname/dbuser/dbpass for host 'localhost' out of an existing
    config.xml so we configure MySQL to match what WaSQL will actually use."""
    import xml.etree.ElementTree as ET
    out: dict = {}
    if not cfg.is_file():
        return out
    try:
        root = ET.parse(str(cfg)).getroot()
    except Exception as e:
        warn(f"could not parse {cfg.name} ({e}); treating it as absent")
        return out
    dbs = {}
    for d in root.findall("database"):
        name = (d.get("name") or "").lower()
        if name:
            dbs[name] = dict(d.attrib)
    allhost = dict(root.find("allhost").attrib) if root.find("allhost") is not None else {}
    hosts = {(h.get("name") or "").lower(): dict(h.attrib) for h in root.findall("host")}
    target = hosts.get("localhost")
    if target is None:
        return out
    merged = dict(allhost)
    seen = set()
    while target is not None and "sameas" in target and target["sameas"].lower() not in seen:
        seen.add(target["sameas"].lower())
        parent = hosts.get(target["sameas"].lower())
        if parent:
            merged.update(parent)
            target = parent
        else:
            break
    merged.update(hosts.get("localhost", {}))
    dbref = (merged.get("database") or "").lower()
    if dbref in dbs:
        merged = {**dbs[dbref], **merged}
    for k in ("dbname", "dbuser", "dbpass", "dbhost", "dbtype"):
        if merged.get(k):
            out[k] = merged[k]
    out["_has_localhost"] = True
    return out


def gather_settings(args) -> Settings:
    """Ask every question up front, then never prompt again."""
    y = args.yes
    here = Path(args.wasql or Path(__file__).resolve().parent).resolve()
    if not (here / "php" / "index.php").is_file():
        die(f"{here} does not look like a WaSQL checkout "
            "(php/index.php missing). Pass --wasql <path>.")

    print(f"\n{C.BOLD}WaSQL local stack installer{C.OFF}")
    print(f"  platform : {platform.platform()}")
    print(f"  wasql    : {here}")
    existing = read_existing_config(here / "config.xml")
    if existing.get("_has_localhost"):
        print(f"  config.xml already defines host 'localhost' -> database "
              f"'{existing.get('dbname', '?')}' (it will be reused, not "
              f"overwritten)")
    print(f"\n{C.BOLD}Answer a few questions, then it runs unattended."
          f"{C.OFF}  (Enter accepts the default)\n")

    wasql = Path(ask("WaSQL directory", str(here), y)).resolve()
    docroot = Path(ask("Apache DocumentRoot", str(args.docroot or wasql), y)).resolve()
    port = int(ask("Apache port", str(args.port or DEFAULT_PORT), y))
    install_packages = (False if args.skip_install else
                        ask_bool("Install Apache/PHP/MySQL if missing?",
                                 not args.skip_install, y))
    db_name = ask("WaSQL database name",
                  args.db_name or existing.get("dbname") or DEFAULT_DB_NAME, y)
    db_user = ask("WaSQL database user",
                  args.db_user or existing.get("dbuser") or DEFAULT_DB_USER, y)
    db_pass = ask("WaSQL database password",
                  args.db_pass or existing.get("dbpass") or DEFAULT_DB_PASS, y)
    root_pass = ask("MySQL root password (blank = leave/keep as-is)",
                    args.mysql_root_pass or "", y)
    sample = ask("Install which sample site?", args.sample or DEFAULT_SAMPLE, y,
                 choices=SAMPLE_CHOICES).lower()
    relax = ask_bool("Relax MySQL sql_mode (recommended for WaSQL)?",
                     not args.strict_sql_mode, y)
    tz = ask("PHP timezone", args.timezone or PHP_INI_SETTINGS["date.timezone"], y)

    s = Settings(wasql=wasql, docroot=docroot, port=port, db_name=db_name,
                 db_user=db_user, db_pass=db_pass, mysql_root_pass=root_pass,
                 install_packages=install_packages, sample=sample,
                 relax_sql_mode=relax, force_config=args.force_config,
                 php_version=args.php_version or "", timezone=tz)

    print(f"\n{C.BOLD}Plan{C.OFF}")
    print(f"  wasql dir      : {s.wasql}")
    print(f"  document root  : {s.docroot}")
    print(f"  url            : http://localhost{'' if s.port == 80 else ':' + str(s.port)}/")
    print(f"  database       : {s.db_name} (user {s.db_user})")
    print(f"  install pkgs   : {'yes' if s.install_packages else 'no (configure only)'}")
    print(f"  sample site    : {s.sample}")
    print(f"  relax sql_mode : {'yes' if s.relax_sql_mode else 'no'}")
    if not y and not ask_bool("\nProceed?", True, False):
        die("aborted", 0)
    return s


# ---------------------------------------------------------------------------
# stack descriptions
# ---------------------------------------------------------------------------

@dataclass
class Apache:
    binary: Optional[Path] = None
    ctl: Optional[Path] = None
    root: Optional[Path] = None          # ServerRoot
    conf: Optional[Path] = None          # main httpd.conf
    conf_dir: Optional[Path] = None      # drop-in dir, if the distro has one
    modules_dir: Optional[Path] = None
    ports_conf: Optional[Path] = None    # debian
    service: Optional[str] = None
    user: str = "daemon"
    group: str = "daemon"
    include_via_conf: bool = True        # append Include to httpd.conf?
    debian_site: bool = False            # use a2ensite/a2enmod


@dataclass
class Php:
    binary: Optional[Path] = None
    home: Optional[Path] = None          # windows: dir holding php.exe
    ini: Optional[Path] = None           # php.ini actually in use
    ini_dirs: list[Path] = field(default_factory=list)  # scan dirs (99-wasql.ini)
    apache_module: Optional[Path] = None  # libphp.so / php8apache2_4.dll
    fpm_service: Optional[str] = None
    version: str = ""


@dataclass
class MySQLPaths:
    client: Optional[Path] = None
    server_bin: Optional[Path] = None
    service: Optional[str] = None
    conf_dir: Optional[Path] = None
    conf_file: Optional[Path] = None


# ---------------------------------------------------------------------------
# base stack
# ---------------------------------------------------------------------------

class Stack:
    """Platform behaviour: locate/install the stack and start its services."""

    label = "generic"

    def __init__(self, s: Settings):
        self.s = s
        self.apache = Apache()
        self.php = Php()
        self.mysql = MySQLPaths()

    # -- discovery / install ------------------------------------------------
    def detect(self):
        raise NotImplementedError

    def install(self):
        raise NotImplementedError

    # -- services -----------------------------------------------------------
    def apache_restart(self) -> Result:
        raise NotImplementedError

    def mysql_start(self) -> Result:
        raise NotImplementedError

    def apache_configtest(self) -> Result:
        if self.apache.ctl:
            return run([str(self.apache.ctl), "configtest"])
        if self.apache.binary:
            return run([str(self.apache.binary), "-t"])
        return Result(1, "", "no apache binary found")

    # -- shared config writers ---------------------------------------------
    def apache_apply(self, block: str):
        """Write the WaSQL apache config and make sure it is included."""
        if self.apache.debian_site:
            target = Path("/etc/apache2/sites-available/000-wasql.conf")
            write_text(target, f"{SENTINEL_BEGIN}\n{block}\n{SENTINEL_END}\n")
            run(["a2dissite", "000-default"], quiet=True)
            run(["a2ensite", "000-wasql"], quiet=True)
            ok(f"wrote {target} (enabled, 000-default disabled)")
            return
        if self.apache.conf_dir and not self.apache.include_via_conf:
            target = self.apache.conf_dir / "wasql.conf"
            write_text(target, f"{SENTINEL_BEGIN}\n{block}\n{SENTINEL_END}\n")
            ok(f"wrote {target}")
            return
        # generic: separate file next to httpd.conf + a single Include line
        assert self.apache.conf, "no httpd.conf located"
        target = self.apache.conf.parent / "wasql.conf"
        write_text(target, f"{SENTINEL_BEGIN}\n{block}\n{SENTINEL_END}\n")
        conf_text = read_text(self.apache.conf)
        backup(self.apache.conf)
        conf_text = self.apache_prepare_main(conf_text)
        inc = f'Include "{posix(target)}"'
        conf_text = replace_block(conf_text, f"# WaSQL local development\n{inc}")
        write_text(self.apache.conf, conf_text)
        ok(f"wrote {target} and included it from {self.apache.conf.name}")

    def apache_prepare_main(self, text: str) -> str:
        """Uncomment the modules WaSQL needs in a stock httpd.conf."""
        for mod in APACHE_MODULES:
            text = uncomment_module(text, mod)
        text = set_listen(text, self.s.port)
        return text

    def php_write_ini(self):
        """Apply PHP_INI_SETTINGS through a scan-dir drop-in when possible."""
        settings = dict(PHP_INI_SETTINGS)
        settings["date.timezone"] = self.s.timezone
        body = "\n".join(f"{k} = {v}" for k, v in settings.items())
        payload = (f"; {SENTINEL_BEGIN}\n; WaSQL local development defaults\n"
                   f"[PHP]\n{body}\n; {SENTINEL_END}\n")
        wrote = False
        for d in self.php.ini_dirs:
            if d and d.is_dir():
                write_text(d / "99-wasql.ini", payload)
                ok(f"wrote {d / '99-wasql.ini'}")
                wrote = True
        if not wrote and self.php.ini:
            backup(self.php.ini)
            text = read_text(self.php.ini)
            for k, v in settings.items():
                text = set_ini_value(text, k, v)
            write_text(self.php.ini, text)
            ok(f"updated {self.php.ini}")
        elif not wrote:
            warn("no php.ini or scan directory found; PHP limits left at defaults")


def posix(p: Path | str) -> str:
    """Apache config wants forward slashes, even on Windows."""
    return str(p).replace("\\", "/")


def uncomment_module(text: str, module: str) -> str:
    pat = re.compile(r"^(\s*)#\s*(LoadModule\s+" + re.escape(module) + r"\s+\S+)\s*$",
                     re.M)
    if pat.search(text):
        return pat.sub(r"\1\2", text)
    return text


def set_listen(text: str, port: int) -> str:
    """Point the first Listen directive at our port (adding one if absent)."""
    pat = re.compile(r"^(\s*)Listen\s+(\S+)\s*$", re.M)
    matches = list(pat.finditer(text))
    if not matches:
        return text
    first = matches[0]
    current = first.group(2)
    want = str(port)
    if current == want or current.endswith(f":{want}"):
        return text
    start, end = first.span()
    return text[:start] + f"{first.group(1)}Listen {want}" + text[end:]


def set_ini_value(text: str, key: str, value: str) -> str:
    pat = re.compile(r"^[;\s]*" + re.escape(key) + r"\s*=.*$", re.M)
    line = f"{key} = {value}"
    if pat.search(text):
        return pat.sub(line, text, count=1)
    return text.rstrip("\n") + f"\n{line}\n"


def enable_win_extension(text: str, ext: str) -> str:
    pat = re.compile(r"^\s*;\s*(extension\s*=\s*" + re.escape(ext) + r")\s*$", re.M)
    if pat.search(text):
        return pat.sub(r"\1", text)
    if re.search(r"^\s*extension\s*=\s*" + re.escape(ext) + r"\s*$", text, re.M):
        return text
    return text.rstrip("\n") + f"\nextension={ext}\n"


def prefer_prefork(text: str) -> str:
    """mod_php is not safe under the event/worker MPMs - switch to prefork."""
    for mpm in ("mpm_event_module", "mpm_worker_module"):
        text = re.sub(r"^(\s*)(LoadModule\s+" + mpm + r"\s+\S+)\s*$",
                      r"\1#\2", text, flags=re.M)
    if re.search(r"^\s*LoadModule\s+mpm_prefork_module", text, re.M):
        return uncomment_module(text, "mpm_prefork_module")
    return text


# ---------------------------------------------------------------------------
# Windows
# ---------------------------------------------------------------------------

class WindowsStack(Stack):
    label = "windows"
    APACHE_SERVICE = "Apache2.4"
    MYSQL_SERVICE = "MySQL"

    def detect(self):
        a = self.apache
        a.binary = first_existing(
            r"C:\tools\Apache24\bin\httpd.exe",
            r"C:\Apache24\bin\httpd.exe",
            r"C:\Program Files\Apache24\bin\httpd.exe",
            r"C:\Apache2*\bin\httpd.exe",
            r"C:\xampp\apache\bin\httpd.exe",
            r"C:\wamp*\bin\apache\apache*\bin\httpd.exe",
        ) or which("httpd")
        if a.binary:
            a.root = a.binary.parent.parent
            a.conf = first_existing(a.root / "conf" / "httpd.conf")
            a.modules_dir = a.root / "modules"
            a.service = self.APACHE_SERVICE
            a.user, a.group = "", ""
        p = self.php
        p.binary = first_existing(
            r"C:\tools\php*\php.exe", r"C:\php*\php.exe",
            r"C:\Program Files\php*\php.exe", r"C:\xampp\php\php.exe",
        ) or which("php")
        if p.binary:
            self._fill_php(p.binary.parent)
        m = self.mysql
        m.client = first_existing(
            r"C:\tools\mysql\current\bin\mysql.exe",
            r"C:\Program Files\MySQL\MySQL Server *\bin\mysql.exe",
            r"C:\tools\mysql*\bin\mysql.exe",
            r"C:\xampp\mysql\bin\mysql.exe",
        ) or which("mysql")
        if m.client:
            m.server_bin = first_existing(m.client.parent / "mysqld.exe")
            m.service = self._find_mysql_service() or self.MYSQL_SERVICE
            m.conf_file = first_existing(
                m.client.parent.parent / "my.ini",
                r"C:\ProgramData\MySQL\MySQL Server *\my.ini",
                r"C:\tools\mysql\current\my.ini",
            )

    def _fill_php(self, home: Path):
        p = self.php
        p.home = home
        p.binary = home / "php.exe"
        p.ini = home / "php.ini"
        p.apache_module = first_existing(home / "php*apache2_4.dll")
        v = run([str(p.binary), "-r", "echo PHP_VERSION;"], quiet=True,
                allow_dry=False)
        p.version = v.out.strip() if v.good else ""

    def _find_mysql_service(self) -> Optional[str]:
        r = powershell("Get-Service | Where-Object {$_.Name -match "
                       "'mysql|mariadb'} | Select-Object -First 1 "
                       "-ExpandProperty Name", allow_dry=False)
        return r.out.strip() or None

    # -- install ------------------------------------------------------------
    def install(self):
        need_apache = self.apache.binary is None
        need_php = self.php.apache_module is None
        need_mysql = self.mysql.client is None
        if not (need_apache or need_php or need_mysql):
            ok("Apache, PHP (thread-safe) and MySQL are all present")
            return
        if need_apache or need_mysql:
            self._ensure_choco()
        if need_apache:
            step("Installing Apache (Chocolatey: apache-httpd)")
            self._choco("apache-httpd")
            self._choco("vcredist140")
        if need_mysql:
            step("Installing MySQL (Chocolatey: mysql)")
            self._choco("mysql")
        if need_php:
            step("Installing PHP (thread-safe build from windows.php.net)")
            self._install_php_windows()
        self.detect()
        missing = [n for n, v in (("apache", self.apache.binary),
                                  ("php", self.php.binary),
                                  ("mysql", self.mysql.client)) if not v]
        if missing:
            die("could not find these after installation: " + ", ".join(missing) +
                "\n  Install them manually, then re-run with --skip-install.")

    def _ensure_choco(self):
        if which("choco"):
            return
        step("Installing Chocolatey (Windows package manager)")
        r = powershell(CHOCO_INSTALL_PS, timeout=900)
        if not r.good:
            die("Chocolatey install failed:\n" + r.text +
                "\n  Install Apache/MySQL manually (or install Chocolatey "
                "yourself) and re-run with --skip-install.")
        choco = first_existing(r"C:\ProgramData\chocolatey\bin\choco.exe")
        if choco:
            os.environ["PATH"] = f"{choco.parent};{os.environ.get('PATH','')}"
        ok("Chocolatey installed")

    def _choco(self, pkg: str, params: str = ""):
        choco = which("choco") or first_existing(
            r"C:\ProgramData\chocolatey\bin\choco.exe")
        if not choco:
            die("choco.exe not found")
        cmd = [str(choco), "install", pkg, "-y", "--no-progress",
               "--ignore-checksums"]
        if params:
            cmd += ["--params", params]
        r = run(cmd, timeout=2400)
        if not r.good and "already installed" not in r.text.lower():
            warn(f"choco install {pkg} returned {r.code}; continuing "
                 f"(see output with --verbose)")

    def _install_php_windows(self):
        """Fetch the newest x64 thread-safe PHP zip (mod_php needs TS)."""
        code, html = http_get(WIN_PHP_RELEASES_URL, timeout=60)
        if code != 200:
            die(f"could not read {WIN_PHP_RELEASES_URL} ({code}). "
                "Install PHP (thread safe, x64) manually and re-run with "
                "--skip-install.")
        cands = []
        for m in re.finditer(r'php-(\d+)\.(\d+)\.(\d+)-Win32-vs(\d+)-x64\.zip',
                             html):
            name = m.group(0)
            if "-nts-" in name or "debug" in name.lower():
                continue
            major, minor, patch, vs = (int(m.group(i)) for i in range(1, 5))
            if self.s.php_version and f"{major}.{minor}" != self.s.php_version:
                continue
            cands.append(((major, minor, patch, vs), name))
        if not cands:
            die("no thread-safe PHP build found on windows.php.net"
                + (f" for branch {self.s.php_version}" if self.s.php_version else ""))
        ver, name = sorted(cands, reverse=True)[0]
        target = Path(f"C:/php-{ver[0]}.{ver[1]}")
        tmp = Path(tempfile.gettempdir()) / name
        download(WIN_PHP_RELEASES_URL + name, tmp, label=name)
        info(f"extracting to {target}")
        if not DRY_RUN:
            target.mkdir(parents=True, exist_ok=True)
            with zipfile.ZipFile(tmp) as z:
                z.extractall(target)
            tmp.unlink(missing_ok=True)
        self._fill_php(target)
        self._add_to_machine_path(target)
        ok(f"PHP {ver[0]}.{ver[1]}.{ver[2]} (TS, vs{ver[3]}) installed at {target}")

    def _add_to_machine_path(self, *dirs: Path):
        parts = [posix(d).replace("/", "\\") for d in dirs if d]
        if not parts:
            return
        script = (
            "$p=[Environment]::GetEnvironmentVariable('Path','Machine');"
            "$add=@(" + ",".join(f"'{d}'" for d in parts) + ");"
            "$cur=$p -split ';';"
            "foreach($a in $add){if($cur -notcontains $a){$p=$p.TrimEnd(';')+';'+$a}};"
            "[Environment]::SetEnvironmentVariable('Path',$p,'Machine');"
        )
        powershell(script)
        for d in parts:
            os.environ["PATH"] = f"{d};{os.environ.get('PATH','')}"

    # -- php config ---------------------------------------------------------
    def php_write_ini(self):
        p = self.php
        if not p.home:
            warn("PHP home unknown; skipping php.ini configuration")
            return
        ini = p.home / "php.ini"
        if not ini.is_file():
            src = first_existing(p.home / "php.ini-development",
                                 p.home / "php.ini-production")
            if src and not DRY_RUN:
                shutil.copy2(src, ini)
                info(f"created php.ini from {src.name}")
        p.ini = ini
        backup(ini)
        text = read_text(ini)
        ext_dir = p.home / "ext"
        text = set_ini_value(text, "extension_dir", f'"{posix(ext_dir)}"')
        enabled = []
        for ext in WIN_EXTENSIONS:
            if (ext_dir / f"php_{ext}.dll").is_file() or DRY_RUN:
                text = enable_win_extension(text, ext)
                enabled.append(ext)
        settings = dict(PHP_INI_SETTINGS)
        settings["date.timezone"] = self.s.timezone
        settings["error_log"] = f'"{posix(self.s.wasql / "logs" / "php_errors.log")}"'
        for k, v in settings.items():
            text = set_ini_value(text, k, v)
        write_text(ini, text)
        ok(f"configured {ini}")
        debug("extensions enabled: " + ", ".join(enabled))

    # -- apache config ------------------------------------------------------
    def apache_prepare_main(self, text: str) -> str:
        text = super().apache_prepare_main(text)
        if self.apache.root:
            text = re.sub(r'^\s*Define\s+SRVROOT\s+".*?"\s*$',
                          f'Define SRVROOT "{posix(self.apache.root)}"',
                          text, count=1, flags=re.M)
        return text

    def php_apache_block(self) -> str:
        p = self.php
        lines = []
        if p.apache_module:
            # LoadFile the shared libs PHP needs; the service does not pick up
            # a freshly changed machine PATH until a reboot.
            for pat in ("libssh2.dll", "libcrypto-*-x64.dll", "libssl-*-x64.dll",
                        "libsodium.dll", "nghttp2.dll", "libzip.dll",
                        "libpq.dll", "libcurl.dll"):
                for hit in sorted(glob.glob(str(p.home / pat))):
                    lines.append(f'LoadFile "{posix(hit)}"')
            mod = "php_module" if "php8" in p.apache_module.name or \
                  "php9" in p.apache_module.name else "php7_module"
            lines.append(f'LoadModule {mod} "{posix(p.apache_module)}"')
            lines.append(f'PHPIniDir "{posix(p.home)}"')
            lines.append('<FilesMatch "\\.(php|phtml)$">')
            lines.append("    SetHandler application/x-httpd-php")
            lines.append("</FilesMatch>")
        else:
            warn("no php*apache2_4.dll found - PHP will not run under Apache")
        return "\n".join(lines)

    # -- services -----------------------------------------------------------
    def apache_restart(self) -> Result:
        svc = self.apache.service or self.APACHE_SERVICE
        exists = powershell(f"if(Get-Service -Name '{svc}' "
                            "-ErrorAction SilentlyContinue){'yes'}")
        if "yes" not in exists.out:
            info(f"registering the {svc} service")
            run([str(self.apache.binary), "-k", "install", "-n", svc])
        r = run([str(self.apache.binary), "-k", "restart", "-n", svc])
        if not r.good:
            run(["sc", "start", svc], quiet=True)
            r = run([str(self.apache.binary), "-k", "start", "-n", svc])
        powershell(f"Set-Service -Name '{svc}' -StartupType Automatic")
        return r

    def mysql_start(self) -> Result:
        svc = self.mysql.service or self.MYSQL_SERVICE
        r = powershell(f"$s=Get-Service -Name '{svc}' -ErrorAction "
                       "SilentlyContinue; if($s){ if($s.Status -ne 'Running')"
                       "{Start-Service $s}; Set-Service $s.Name -StartupType "
                       "Automatic; 'running' } else { 'missing' }")
        if "missing" in r.out and self.mysql.server_bin:
            info("MySQL service not registered; installing it")
            run([str(self.mysql.server_bin), "--install", svc])
            r = powershell(f"Start-Service '{svc}'; 'running'")
        return r


# ---------------------------------------------------------------------------
# macOS
# ---------------------------------------------------------------------------

class MacStack(Stack):
    label = "macos"

    def __init__(self, s: Settings):
        super().__init__(s)
        self.user = invoking_user()
        self.brew = first_existing("/opt/homebrew/bin/brew",
                                   "/usr/local/bin/brew") or which("brew")
        self.prefix = Path("/opt/homebrew") if self.brew and \
            str(self.brew).startswith("/opt/homebrew") else Path("/usr/local")

    # brew refuses to run as root, so bounce back to the invoking user
    def _brew(self, *args: str, timeout: int = 2400) -> Result:
        if not self.brew:
            return Result(127, "", "brew not found")
        if os.geteuid() == 0 and self.user:
            return run(["sudo", "-u", self.user, "-H", str(self.brew), *args],
                       timeout=timeout)
        return run([str(self.brew), *args], timeout=timeout)

    def detect(self):
        if self.brew:
            r = run([str(self.brew), "--prefix"], quiet=True, allow_dry=False)
            if r.good and r.out:
                self.prefix = Path(r.out.strip())
        pfx = self.prefix
        a = self.apache
        a.binary = first_existing(pfx / "opt/httpd/bin/httpd", pfx / "bin/httpd")
        a.ctl = first_existing(pfx / "bin/apachectl", pfx / "opt/httpd/bin/apachectl")
        a.root = first_existing(pfx / "opt/httpd")
        a.conf = first_existing(pfx / "etc/httpd/httpd.conf")
        a.modules_dir = first_existing(pfx / "opt/httpd/lib/httpd/modules")
        a.user, a.group = "_www", "_www"
        a.service = "httpd"
        p = self.php
        p.binary = first_existing(pfx / "opt/php/bin/php", pfx / "bin/php") or which("php")
        p.apache_module = first_existing(pfx / "opt/php/lib/httpd/modules/libphp.so",
                                        pfx / "lib/httpd/modules/libphp.so")
        if p.binary:
            v = run([str(p.binary), "-r", "echo PHP_VERSION;"], quiet=True,
                    allow_dry=False)
            p.version = v.out.strip()
            r = run([str(p.binary), "-i"], quiet=True, allow_dry=False)
            m = re.search(r"Loaded Configuration File => (\S+)", r.out)
            if m and m.group(1) != "(none)":
                p.ini = Path(m.group(1))
            m = re.search(r"Scan this dir for additional .ini files => (\S+)", r.out)
            if m and m.group(1) != "(none)":
                p.ini_dirs = [Path(m.group(1))]
        m = self.mysql
        m.client = first_existing(pfx / "opt/mysql/bin/mysql", pfx / "bin/mysql") or which("mysql")
        m.server_bin = first_existing(pfx / "opt/mysql/bin/mysqld")
        m.conf_file = first_existing(pfx / "etc/my.cnf")
        m.conf_dir = first_existing(pfx / "etc/my.cnf.d")
        m.service = "mysql"

    def install(self):
        if not self.brew:
            step("Installing Homebrew")
            if not self.user:
                die("Homebrew cannot be installed as root. Run this script as a "
                    "normal user (it will sudo where needed).")
            r = run(["sudo", "-u", self.user, "-H", "bash", "-c",
                     f'NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL {BREW_INSTALL_URL})"'],
                    timeout=3600)
            if not r.good:
                die("Homebrew install failed:\n" + r.text)
            self.brew = first_existing("/opt/homebrew/bin/brew", "/usr/local/bin/brew")
            self.detect()
        want = []
        if not self.apache.binary:
            want.append("httpd")
        if not self.php.apache_module:
            want.append("php")
        if not self.mysql.client:
            want.append("mysql")
        if not want:
            ok("httpd, php and mysql are already installed via Homebrew")
            return
        step(f"Installing via Homebrew: {', '.join(want)}")
        self._brew("update", timeout=1200)
        for pkg in want:
            r = self._brew("install", pkg)
            if not r.good and "already installed" not in r.text.lower():
                warn(f"brew install {pkg} failed:\n{r.text[:400]}")
        self.detect()

    def php_apache_block(self) -> str:
        p = self.php
        if not p.apache_module:
            warn("brew php libphp.so not found - PHP will not run under Apache")
            return ""
        return "\n".join([
            f'LoadModule php_module "{posix(p.apache_module)}"',
            '<FilesMatch "\\.(php|phtml)$">',
            "    SetHandler application/x-httpd-php",
            "</FilesMatch>",
        ])

    def apache_prepare_main(self, text: str) -> str:
        text = super().apache_prepare_main(text)
        return prefer_prefork(text)

    def apache_restart(self) -> Result:
        # `sudo brew services` is the documented way to run httpd on port 80,
        # so this one stays as root instead of dropping to the invoking user
        r = run([str(self.brew), "services", "restart", "httpd"], quiet=True) \
            if self.brew else Result(1, "", "brew not found")
        if not r.good and self.apache.ctl:
            run([str(self.apache.ctl), "-k", "stop"], quiet=True)
            time.sleep(1)
            r = run([str(self.apache.ctl), "-k", "start"])
        return r

    def mysql_start(self) -> Result:
        r = self._brew("services", "start", "mysql")
        if not r.good:
            warn("brew services start mysql failed; trying mysql.server")
            srv = first_existing(self.prefix / "opt/mysql/bin/mysqld_safe")
            if srv:
                run(["bash", "-c", f"{srv} --user=mysql &"], quiet=True)
                time.sleep(5)
        for _ in range(20):
            if port_in_use(3306):
                return Result(0, "mysql up", "")
            time.sleep(1)
        return r


# ---------------------------------------------------------------------------
# Linux
# ---------------------------------------------------------------------------

LINUX_PROFILES = {
    "apt": dict(
        install=["apt-get", "install", "-y", "--no-install-recommends"],
        refresh=["apt-get", "update"],
        apache=["apache2"],
        php=["php", "php-cli", "libapache2-mod-php", "php-mysql", "php-xml",
             "php-mbstring", "php-curl", "php-zip", "php-gd", "php-intl",
             "php-bcmath", "php-soap", "php-ldap", "php-sqlite3", "php-opcache"],
        mysql=[["mysql-server"], ["mariadb-server"]],
        extra=["unzip", "curl"],
        apache_service="apache2", apache_user="www-data",
        php_mode="module",
    ),
    "dnf": dict(
        install=["dnf", "install", "-y", "--setopt=strict=0"],
        refresh=["dnf", "makecache"],
        apache=["httpd"],
        php=["php", "php-cli", "php-fpm", "php-mysqlnd", "php-xml",
             "php-mbstring", "php-gd", "php-intl", "php-soap", "php-ldap",
             "php-pdo", "php-opcache", "php-process", "php-bcmath",
             "php-sodium", "php-zip", "php-pecl-zip", "php-json"],
        mysql=[["mysql-server"], ["community-mysql-server"], ["mariadb-server"]],
        extra=["unzip", "curl", "policycoreutils-python-utils"],
        apache_service="httpd", apache_user="apache",
        php_mode="fpm",
    ),
    "pacman": dict(
        install=["pacman", "-S", "--noconfirm", "--needed"],
        refresh=["pacman", "-Sy"],
        apache=["apache"],
        php=["php", "php-apache", "php-gd", "php-intl", "php-sqlite",
             "php-sodium"],
        mysql=[["mariadb"]],
        extra=["unzip", "curl"],
        apache_service="httpd", apache_user="http",
        php_mode="module",
    ),
    "zypper": dict(
        install=["zypper", "--non-interactive", "install"],
        refresh=["zypper", "--non-interactive", "refresh"],
        apache=["apache2"],
        php=["php8", "apache2-mod_php8", "php8-mysql", "php8-mbstring",
             "php8-curl", "php8-zip", "php8-gd", "php8-intl", "php8-openssl",
             "php8-soap", "php8-ldap", "php8-sqlite", "php8-fileinfo",
             "php8-exif", "php8-sockets", "php8-bcmath"],
        mysql=[["mariadb"]],
        extra=["unzip", "curl"],
        apache_service="apache2", apache_user="wwwrun",
        php_mode="module",
    ),
}


class LinuxStack(Stack):
    label = "linux"

    def __init__(self, s: Settings):
        super().__init__(s)
        self.pm = self._detect_pm()
        self.profile = LINUX_PROFILES.get(self.pm, {})
        self.distro = self._distro_id()

    @staticmethod
    def _detect_pm() -> str:
        for pm in ("apt-get", "dnf", "yum", "pacman", "zypper"):
            if which(pm):
                return {"apt-get": "apt", "yum": "dnf"}.get(pm, pm)
        return ""

    @staticmethod
    def _distro_id() -> str:
        txt = read_text(Path("/etc/os-release"))
        m = re.search(r"^ID=\"?([\w.-]+)", txt, re.M)
        return m.group(1) if m else "linux"

    # -- discovery ----------------------------------------------------------
    def detect(self):
        deb = self.pm == "apt" or Path("/etc/apache2/apache2.conf").is_file()
        suse = self.pm == "zypper"
        a = self.apache
        a.binary = which("apache2", "httpd")
        a.ctl = which("apache2ctl", "apachectl")
        a.service = self.profile.get("apache_service") or ("apache2" if deb else "httpd")
        a.user = a.group = self.profile.get("apache_user", "www-data")
        if deb:
            a.conf = first_existing("/etc/apache2/apache2.conf")
            a.conf_dir = first_existing("/etc/apache2/conf-available")
            a.ports_conf = first_existing("/etc/apache2/ports.conf")
            a.modules_dir = first_existing("/usr/lib/apache2/modules")
            a.debian_site = True
            a.include_via_conf = False
        elif suse:
            a.conf = first_existing("/etc/apache2/httpd.conf")
            a.conf_dir = first_existing("/etc/apache2/vhosts.d")
            a.ports_conf = first_existing("/etc/apache2/listen.conf")
            a.modules_dir = first_existing("/usr/lib64/apache2", "/usr/lib/apache2")
            a.include_via_conf = False
        else:
            a.conf = first_existing("/etc/httpd/conf/httpd.conf")
            a.conf_dir = first_existing("/etc/httpd/conf.d")
            a.modules_dir = first_existing("/etc/httpd/modules", "/usr/lib64/httpd/modules")
            a.include_via_conf = False
        p = self.php
        p.binary = which("php")
        if p.binary:
            r = run([str(p.binary), "-r", "echo PHP_VERSION;"], quiet=True,
                    allow_dry=False)
            p.version = r.out.strip()
            i = run([str(p.binary), "-i"], quiet=True, allow_dry=False)
            m = re.search(r"Loaded Configuration File => (\S+)", i.out)
            if m and m.group(1) != "(none)":
                p.ini = Path(m.group(1))
        branch = ".".join(p.version.split(".")[:2]) if p.version else "*"
        p.ini_dirs = [Path(d) for d in
                      glob.glob(f"/etc/php/{branch}/apache2/conf.d") +
                      glob.glob(f"/etc/php/{branch}/cli/conf.d") +
                      glob.glob(f"/etc/php/{branch}/fpm/conf.d") +
                      glob.glob("/etc/php.d") +
                      glob.glob("/etc/php/conf.d") +
                      glob.glob("/etc/php8/conf.d") +
                      glob.glob("/etc/php8/apache2/conf.d") +
                      glob.glob("/etc/php8/fastcgi/conf.d")
                      if Path(d).is_dir()]
        p.apache_module = first_existing(
            "/usr/lib/apache2/modules/libphp*.so",
            "/usr/lib64/httpd/modules/libphp*.so",
            "/usr/lib/httpd/modules/libphp*.so",
        )
        if self.profile.get("php_mode") == "fpm" or (
                not p.apache_module and which("php-fpm")):
            p.fpm_service = "php-fpm" if which("php-fpm") or \
                Path("/usr/sbin/php-fpm").exists() else None
            if not p.fpm_service:
                svc = first_existing("/lib/systemd/system/php*-fpm.service",
                                     "/usr/lib/systemd/system/php*-fpm.service")
                if svc:
                    p.fpm_service = svc.stem
        m = self.mysql
        m.client = which("mysql", "mariadb")
        m.server_bin = which("mysqld", "mariadbd")
        m.service = self._mysql_service()
        m.conf_dir = first_existing("/etc/mysql/conf.d", "/etc/my.cnf.d",
                                    "/etc/mysql/mysql.conf.d")
        m.conf_file = first_existing("/etc/my.cnf")

    @staticmethod
    def _mysql_service() -> Optional[str]:
        for svc in ("mysql", "mysqld", "mariadb"):
            r = run(["systemctl", "list-unit-files", f"{svc}.service"],
                    quiet=True, allow_dry=False)
            if r.good and f"{svc}.service" in r.out:
                return svc
        return None

    # -- install ------------------------------------------------------------
    def _available(self, pkgs: list[str]) -> list[str]:
        """Filter to packages this distro actually ships (names vary a lot)."""
        if self.pm == "apt":
            out = []
            for p in pkgs:
                r = run(["apt-cache", "policy", p], quiet=True, allow_dry=False)
                if r.good and "Candidate:" in r.out and "(none)" not in r.out:
                    out.append(p)
                else:
                    debug(f"skip unavailable package {p}")
            return out
        return pkgs  # dnf(strict=0)/pacman --needed/zypper tolerate extras

    def _install(self, pkgs: list[str], label: str) -> bool:
        pkgs = self._available(pkgs)
        if not pkgs:
            return False
        info(f"{label}: {' '.join(pkgs)}")
        env = {"DEBIAN_FRONTEND": "noninteractive"} if self.pm == "apt" else None
        r = run(self.profile["install"] + pkgs, timeout=3600, env=env)
        if not r.good:
            warn(f"package install returned {r.code} for {label}: "
                 f"{r.text.splitlines()[-1] if r.text else ''}")
        return r.good

    def install(self):
        if not self.pm:
            die("no supported package manager found (apt/dnf/yum/pacman/zypper). "
                "Install Apache, PHP and MySQL manually, then re-run with "
                "--skip-install.")
        step(f"Installing packages with {self.pm} ({self.distro})")
        run(self.profile["refresh"], timeout=1800, quiet=True)
        self._install(self.profile["apache"], "apache")
        self._install(self.profile["php"], "php")
        self._install(self.profile.get("extra", []), "tools")
        if not which("mysql", "mariadb"):
            for group in self.profile["mysql"]:
                if self._install(group, "database server") and which("mysql", "mariadb"):
                    break
        self.detect()
        if self.pm == "apt":
            run(["a2enmod", "rewrite", "headers", "expires", "setenvif"], quiet=True)
            if self.php.fpm_service and not self.php.apache_module:
                run(["a2enmod", "proxy", "proxy_fcgi"], quiet=True)
                run(["a2enconf", f"{self.php.version[:3]}-fpm"], quiet=True)
        if self.pm == "zypper":
            run(["a2enmod", "rewrite", "php8", "headers"], quiet=True)
        if self.pm == "pacman":
            self._init_mariadb_datadir()
        if not self.apache.binary or not self.php.binary or not self.mysql.client:
            die("apache/php/mysql still missing after install; "
                "check the package manager output with --verbose")

    def _init_mariadb_datadir(self):
        if Path("/var/lib/mysql/mysql").is_dir():
            return
        info("initialising the MariaDB data directory")
        run(["mariadb-install-db", "--user=mysql", "--basedir=/usr",
             "--datadir=/var/lib/mysql"], timeout=600)

    # -- config -------------------------------------------------------------
    def php_apache_block(self) -> str:
        p = self.php
        if p.apache_module and self.pm in ("pacman",):
            return "\n".join([
                f'LoadModule php_module "{posix(p.apache_module)}"',
                'Include conf/extra/php_module.conf',
            ])
        # debian/suse/rhel wire php up through their own conf snippets
        return ""

    def apache_prepare_main(self, text: str) -> str:
        if self.pm == "pacman":
            text = prefer_prefork(text)
            for mod in APACHE_MODULES:
                text = uncomment_module(text, mod)
        return text

    def apache_apply(self, block: str):
        # keep the distro layout: sites-available (debian) / conf.d / vhosts.d
        if self.pm == "pacman":
            target = Path("/etc/httpd/conf/extra/wasql.conf")
            write_text(target, f"{SENTINEL_BEGIN}\n{block}\n{SENTINEL_END}\n")
            conf = self.apache.conf
            if conf:
                backup(conf)
                text = self.apache_prepare_main(read_text(conf))
                text = set_listen(text, self.s.port)
                text = replace_block(text, f'Include conf/extra/wasql.conf')
                write_text(conf, text)
            ok(f"wrote {target}")
            return
        if self.apache.ports_conf and self.s.port != 80:
            backup(self.apache.ports_conf)
            write_text(self.apache.ports_conf,
                       set_listen(read_text(self.apache.ports_conf), self.s.port))
        super().apache_apply(block)

    def selinux_fixup(self):
        r = run(["getenforce"], quiet=True, allow_dry=False)
        if not r.good or "Enforcing" not in r.out:
            return
        step("Adjusting SELinux for the WaSQL paths")
        run(["setsebool", "-P", "httpd_can_network_connect_db", "1"], quiet=True)
        run(["setsebool", "-P", "httpd_can_network_connect", "1"], quiet=True)
        run(["setsebool", "-P", "httpd_execmem", "1"], quiet=True)
        paths_ro = [self.s.wasql, self.s.docroot]
        paths_rw = [self.s.wasql / "php" / "temp", self.s.wasql / "logs",
                    self.s.wasql / "php" / "schema", self.s.docroot / "w_min",
                    self.s.docroot / "images"]
        if which("semanage"):
            for p in paths_ro:
                run(["semanage", "fcontext", "-a", "-t", "httpd_sys_content_t",
                     f"{p}(/.*)?"], quiet=True)
            for p in paths_rw:
                run(["semanage", "fcontext", "-a", "-t", "httpd_sys_rw_content_t",
                     f"{p}(/.*)?"], quiet=True)
            for p in paths_ro:
                run(["restorecon", "-R", str(p)], quiet=True)
            ok("SELinux file contexts applied")
        else:
            for p in paths_ro:
                run(["chcon", "-R", "-t", "httpd_sys_content_t", str(p)], quiet=True)
            for p in paths_rw:
                run(["chcon", "-R", "-t", "httpd_sys_rw_content_t", str(p)], quiet=True)
            warn("semanage not available; used chcon (labels reset on relabel)")

    # -- services -----------------------------------------------------------
    def apache_restart(self) -> Result:
        svc = self.apache.service
        if self.php.fpm_service:
            run(["systemctl", "enable", "--now", self.php.fpm_service], quiet=True)
        run(["systemctl", "enable", svc], quiet=True)
        r = run(["systemctl", "restart", svc])
        if not r.good:
            r2 = run(["systemctl", "status", svc, "--no-pager", "-l"], quiet=True)
            r.err = (r.err + "\n" + r2.out).strip()
        return r

    def mysql_start(self) -> Result:
        svc = self.mysql.service or self._mysql_service()
        if not svc:
            return Result(1, "", "no mysql/mariadb service found")
        self.mysql.service = svc
        run(["systemctl", "enable", svc], quiet=True)
        r = run(["systemctl", "restart", svc])
        for _ in range(30):
            if port_in_use(3306) or Path("/var/run/mysqld/mysqld.sock").exists():
                return Result(0, f"{svc} running", "")
            time.sleep(1)
        return r


# ---------------------------------------------------------------------------
# MySQL configuration
# ---------------------------------------------------------------------------

class MySQLAdmin:
    """Talks to the local server through the mysql client, trying the login
    strategies a fresh install could plausibly be in."""

    def __init__(self, client: Path, root_pass: str, allow_sudo: bool):
        self.client = client
        self.root_pass = root_pass
        self.allow_sudo = allow_sudo and not IS_WIN
        self.strategy: Optional[dict] = None

    def _candidates(self) -> list[dict]:
        c = []
        if self.root_pass:
            c.append(dict(user="root", password=self.root_pass, sudo=False))
            if self.allow_sudo:
                c.append(dict(user="root", password=self.root_pass, sudo=True))
        c.append(dict(user="root", password="", sudo=False))
        if self.allow_sudo:
            c.append(dict(user="root", password="", sudo=True))
            c.append(dict(user="root", password="", sudo=True, socket=True))
        return c

    def _cmd(self, strat: dict, sql: str, database: Optional[str]) -> tuple[list[str], Optional[Path]]:
        args: list[str] = []
        tmp: Optional[Path] = None
        if strat.get("password"):
            fd, name = tempfile.mkstemp(prefix="wasql-my-", suffix=".cnf")
            os.close(fd)
            tmp = Path(name)
            pw = strat["password"].replace("\\", "\\\\").replace('"', '\\"')
            write_text(tmp, f'[client]\nuser={strat["user"]}\npassword="{pw}"\n', 0o600)
            args += [f"--defaults-file={tmp}"]
        else:
            args += ["--user=" + strat["user"]]
        args += ["--batch", "--raw", "--connect-timeout=10"]
        if database:
            args += [database]
        args += ["-e", sql]
        cmd = [str(self.client)] + args
        if strat.get("sudo") and os.geteuid() != 0:
            cmd = ["sudo", "-n"] + cmd
        elif strat.get("sudo"):
            pass  # already root
        return cmd, tmp

    def sql(self, statements: str, database: Optional[str] = None,
            quiet: bool = True) -> Result:
        if DRY_RUN and not re.match(r"\s*(SELECT|SHOW)\b", statements, re.I):
            info(f"{C.DIM}[dry-run] mysql: {statements[:120]}{C.OFF}")
            return Result(0, "", "")
        strats = [self.strategy] if self.strategy else self._candidates()
        last = Result(1, "", "no mysql login strategy worked")
        for strat in strats:
            if strat is None:
                continue
            cmd, tmp = self._cmd(strat, statements, database)
            r = run(cmd, quiet=quiet, timeout=600, allow_dry=False)
            if tmp:
                tmp.unlink(missing_ok=True)
            if r.good:
                self.strategy = strat
                return r
            last = r
            if "Access denied" not in r.text and "denied" not in r.text.lower():
                # a real SQL error, not an auth problem - stop guessing
                if self.strategy or "ERROR 1" in r.text:
                    return r
        return last

    def connect_ok(self) -> bool:
        return self.sql("SELECT 1;").good

    def describe_login(self) -> str:
        if not self.strategy:
            return "unknown"
        bits = ["root"]
        if self.strategy.get("password"):
            bits.append("password")
        else:
            bits.append("no password")
        if self.strategy.get("sudo"):
            bits.append("via sudo socket")
        return ", ".join(bits)


def sql_quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def setup_database(s: Settings, admin: MySQLAdmin) -> bool:
    db, user, pw = s.db_name, s.db_user, sql_quote(s.db_pass)
    if not admin.connect_ok():
        warn("could not log into MySQL as root automatically.\n"
             "         Create the database manually:\n"
             f"           CREATE DATABASE `{db}` CHARACTER SET utf8mb4;\n"
             f"           CREATE USER '{user}'@'%' IDENTIFIED BY '{s.db_pass}';\n"
             f"           GRANT ALL PRIVILEGES ON *.* TO '{user}'@'%' WITH GRANT OPTION;")
        return False
    info(f"connected to MySQL ({admin.describe_login()})")

    if s.mysql_root_pass and not (admin.strategy or {}).get("password"):
        r = admin.sql("ALTER USER 'root'@'localhost' IDENTIFIED BY '"
                      + sql_quote(s.mysql_root_pass) + "'; FLUSH PRIVILEGES;")
        if r.good:
            ok("set the MySQL root password")
            admin.strategy = dict(user="root", password=s.mysql_root_pass, sudo=False)
            admin.root_pass = s.mysql_root_pass
        else:
            warn(f"could not set the root password: {r.text.splitlines()[:1]}")

    r = admin.sql(f"CREATE DATABASE IF NOT EXISTS `{db}` "
                  "CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    if not r.good:
        warn(f"create database failed: {r.text}")
        return False
    ok(f"database `{db}` ready")

    grants = "; ".join(
        [f"CREATE USER IF NOT EXISTS '{user}'@'{h}' IDENTIFIED BY '{pw}'"
         for h in ("localhost", "%")] +
        [f"ALTER USER '{user}'@'{h}' IDENTIFIED BY '{pw}'"
         for h in ("localhost", "%")] +
        [f"GRANT ALL PRIVILEGES ON *.* TO '{user}'@'{h}' WITH GRANT OPTION"
         for h in ("localhost", "%")] +
        ["FLUSH PRIVILEGES"]) + ";"
    r = admin.sql(grants)
    if not r.good and re.search(r"policy|password", r.text, re.I):
        info("password policy rejected the password; relaxing it for this box")
        admin.sql("SET GLOBAL validate_password.policy=LOW;", quiet=True)
        admin.sql("SET GLOBAL validate_password.length=4;", quiet=True)
        admin.sql("SET GLOBAL validate_password_policy=LOW;", quiet=True)
        admin.sql("SET GLOBAL validate_password_length=4;", quiet=True)
        r = admin.sql(grants)
    if not r.good:
        warn(f"could not create/grant the WaSQL user: {r.text}")
        return False
    ok(f"user '{user}' created with full privileges")
    return True


def tune_mysql(s: Settings, admin: MySQLAdmin, stack: Stack) -> None:
    """Relax sql_mode (WaSQL predates STRICT/ONLY_FULL_GROUP_BY) and raise
    max_allowed_packet so backups/restores work."""
    if not s.relax_sql_mode:
        return
    persisted = admin.sql(
        "SET PERSIST sql_mode='NO_ENGINE_SUBSTITUTION'; "
        "SET PERSIST max_allowed_packet=268435456;").good
    if persisted:
        ok("sql_mode and max_allowed_packet persisted (SET PERSIST)")
        return
    block = ("[mysqld]\n"
             "sql_mode=NO_ENGINE_SUBSTITUTION\n"
             "max_allowed_packet=256M\n"
             "innodb_strict_mode=0\n")
    target = None
    if stack.mysql.conf_dir and stack.mysql.conf_dir.is_dir():
        target = stack.mysql.conf_dir / "99-wasql.cnf"
        write_text(target, f"# {SENTINEL_BEGIN}\n{block}# {SENTINEL_END}\n")
    elif stack.mysql.conf_file and stack.mysql.conf_file.is_file():
        target = stack.mysql.conf_file
        backup(target)
        write_text(target, replace_block(read_text(target), block))
    if target:
        ok(f"wrote MySQL tuning to {target}")
        r = stack.mysql_start()
        if not r.good:
            warn("MySQL did not restart cleanly after tuning; check the service")
    else:
        warn("could not find a MySQL config dir; sql_mode left at the default "
             "(WaSQL may complain about strict mode)")


# ---------------------------------------------------------------------------
# WaSQL side of the install
# ---------------------------------------------------------------------------

def wasql_config_xml(s: Settings) -> None:
    """Create config.xml if absent; otherwise leave the developer's alone."""
    cfg = s.wasql / "config.xml"
    existing = read_existing_config(cfg)
    if cfg.is_file() and existing.get("_has_localhost") and not s.force_config:
        ok(f"config.xml already maps localhost -> `{existing.get('dbname')}` "
           "(left untouched)")
        return
    port_hosts = ""
    if s.port != 80:
        port_hosts = (f'\t<host name="localhost:{s.port}" sameas="localhost" />\n'
                      f'\t<host name="127.0.0.1:{s.port}" sameas="localhost" />\n')
    body = f"""<hosts>
\t<!--
\t\tGenerated by install_localhost.py for local development.
\t\tsample.config.xml documents every available attribute.
\t-->
\t<database
\t\tname="wasql_local"
\t\tdisplayname="WaSQL Local"
\t\tdbtype="mysqli"
\t\tdbhost="{s.db_host}"
\t\tdbname="{s.db_name}"
\t\tdbuser="{s.db_user}"
\t\tdbpass="{s.db_pass}"
\t/>
\t<allhost
\t\tpaging="50"
\t\tmarkdown="1"
\t\tdatabase_sessions="1"
\t\taccess="all"
\t\tmissing_page="passthru"
\t/>
\t<host name="localhost" database="wasql_local" cron="1" insecure="1" />
\t<host name="127.0.0.1" sameas="localhost" />
{port_hosts}</hosts>
"""
    if cfg.is_file():
        backup(cfg)
        if not existing.get("_has_localhost"):
            # keep the developer's file, just add a localhost host + database
            text = read_text(cfg)
            add = (f'\t<database name="wasql_local" displayname="WaSQL Local" '
                   f'dbtype="mysqli" dbhost="{s.db_host}" dbname="{s.db_name}" '
                   f'dbuser="{s.db_user}" dbpass="{s.db_pass}" />\n'
                   f'\t<host name="localhost" database="wasql_local" cron="1" />\n'
                   f'\t<host name="127.0.0.1" sameas="localhost" />\n')
            if "</hosts>" in text:
                text = text.replace("</hosts>", add + "</hosts>", 1)
                write_text(cfg, text)
                ok("added a localhost host entry to the existing config.xml")
                return
        write_text(cfg, body)
        ok(f"rewrote {cfg} (previous copy saved as config.xml.wasql-bak)")
        return
    write_text(cfg, body)
    ok(f"created {cfg}")


def wasql_filesystem(s: Settings, stack: Stack) -> None:
    """Directories, permissions and .htaccess WaSQL expects to exist."""
    web_user = stack.apache.user if not IS_WIN else None
    ensure_dir(s.wasql / "php" / "temp", writable=True, owner=web_user)
    ensure_dir(s.wasql / "logs", writable=True, owner=web_user)
    # the setup wizard unzips a site template inside php/schema, then removes it
    if not IS_WIN and (s.wasql / "php" / "schema").is_dir() and not DRY_RUN:
        try:
            os.chmod(s.wasql / "php" / "schema", 0o777)
        except OSError as e:
            debug(f"chmod php/schema: {e}")
    ensure_dir(s.docroot, writable=False)
    ensure_dir(s.docroot / "images", writable=True, owner=web_user)
    ensure_dir(s.docroot / "w_min", writable=True, owner=web_user)
    ensure_traversable(s.wasql)
    if s.docroot != s.wasql:
        ensure_traversable(s.docroot)

    ht = s.docroot / ".htaccess"
    sample = s.wasql / "sample.htaccess"
    if not ht.is_file() and sample.is_file() and not DRY_RUN:
        shutil.copy2(sample, ht)
        ok(f"created {ht} from sample.htaccess")
    if s.docroot != s.wasql:
        # aliases cover /php and /wfiles, but a symlink keeps relative paths sane
        for name in ("php", "wfiles"):
            link = s.docroot / name
            target = s.wasql / name
            if not link.exists() and target.is_dir() and not IS_WIN and not DRY_RUN:
                try:
                    link.symlink_to(target)
                    debug(f"symlinked {link} -> {target}")
                except OSError as e:
                    debug(f"symlink {link}: {e}")
    ok("WaSQL directories and permissions prepared")


def apache_vhost(s: Settings, stack: Stack) -> str:
    w, d = posix(s.wasql), posix(s.docroot)
    php_block = getattr(stack, "php_apache_block", lambda: "")()
    dir_opts = "Options Indexes FollowSymLinks ExecCGI"
    # when the docroot IS the wasql dir one Directory block covers both
    wasql_dir_block = "" if d == w else f"""
    <Directory "{w}">
        {dir_opts}
        AllowOverride All
        Require local
    </Directory>
"""
    body = f"""# WaSQL local development - {s.wasql}
{php_block}

<VirtualHost *:{s.port}>
    ServerName localhost
    ServerAlias 127.0.0.1
    DocumentRoot "{d}"
    DirectoryIndex index.php index.html index.htm

    Alias /php/ "{w}/php/"
    Alias /wfiles/ "{w}/wfiles/"
{wasql_dir_block}
    <Directory "{d}">
        {dir_opts}
        AllowOverride All
        Require local

        RewriteEngine On
        RewriteBase /
        # let real files and directories through
        RewriteCond %{{REQUEST_FILENAME}} !-f
        RewriteCond %{{REQUEST_FILENAME}} !-d
        RewriteCond %{{REQUEST_URI}} !=/server-status
        # everything else is a WaSQL page
        RewriteRule ^(.*)$ /php/index.php?_view=$1 [L,QSA]
        RewriteRule ^$ /php/index.php?_view=index [L,QSA]
    </Directory>
</VirtualHost>
"""
    return body


def configure_apache(s: Settings, stack: Stack) -> bool:
    step("Configuring Apache")
    if not stack.apache.conf and not stack.apache.conf_dir:
        warn("no Apache configuration directory found; skipping")
        return False
    if stack.apache.conf and stack.apache.include_via_conf is False and \
            stack.apache.conf.is_file() and not stack.apache.debian_site:
        # distro layout: still make sure the modules we need are on
        backup(stack.apache.conf)
        text = stack.apache_prepare_main(read_text(stack.apache.conf))
        if s.port != 80 and not stack.apache.ports_conf:
            text = set_listen(text, s.port)
        write_text(stack.apache.conf, text)
    stack.apache_apply(apache_vhost(s, stack))
    t = stack.apache_configtest()
    if not t.good and "Syntax OK" not in t.text:
        warn("apache configtest reported a problem:\n" +
             "\n".join(t.text.splitlines()[-12:]))
        return False
    ok("apache configuration syntax is valid")
    return True


# ---------------------------------------------------------------------------
# verification
# ---------------------------------------------------------------------------

CHECK_PHP = r"""<?php
// temporary file written by install_localhost.py - safe to delete
header('Content-Type: application/json');
$exts = array_map('strtolower', get_loaded_extensions());
$w = array();
foreach (array('__TEMP__','__LOGS__','__WMIN__','__IMAGES__') as $p) {
    $w[$p] = is_dir($p) ? is_writable($p) : null;
}
$db = array('ok' => false, 'error' => 'mysqli missing');
if (function_exists('mysqli_connect')) {
    $c = @mysqli_connect('__DBHOST__', '__DBUSER__', '__DBPASS__', '__DBNAME__');
    if ($c) { $db = array('ok' => true, 'error' => ''); @mysqli_close($c); }
    else { $db = array('ok' => false, 'error' => mysqli_connect_error()); }
}
echo json_encode(array(
    'php' => PHP_VERSION,
    'sapi' => PHP_SAPI,
    'ini' => array(
        'memory_limit' => ini_get('memory_limit'),
        'post_max_size' => ini_get('post_max_size'),
        'upload_max_filesize' => ini_get('upload_max_filesize'),
        'timezone' => date_default_timezone_get(),
    ),
    'extensions' => $exts,
    'writable' => $w,
    'db' => $db,
));
"""


def verify(s: Settings, stack: Stack) -> dict:
    """End-to-end check through Apache: PHP version, extensions, writability
    and an actual mysqli connection using the configured credentials."""
    step("Verifying the stack through Apache")
    if DRY_RUN:
        info(f"{C.DIM}[dry-run] would fetch /_wasql_install_check.php{C.OFF}")
        return {}
    base = f"http://localhost{'' if s.port == 80 else ':' + str(s.port)}"
    check = s.docroot / "_wasql_install_check.php"
    body = (CHECK_PHP
            .replace("__TEMP__", posix(s.wasql / "php" / "temp"))
            .replace("__LOGS__", posix(s.wasql / "logs"))
            .replace("__WMIN__", posix(s.docroot / "w_min"))
            .replace("__IMAGES__", posix(s.docroot / "images"))
            .replace("__DBHOST__", s.db_host)
            .replace("__DBUSER__", s.db_user)
            .replace("__DBPASS__", s.db_pass)
            .replace("__DBNAME__", s.db_name))
    write_text(check, body)
    result: dict = {}
    try:
        code, text = 0, ""
        for _ in range(12):
            code, text = http_get(f"{base}/_wasql_install_check.php", timeout=20)
            if code:
                break
            time.sleep(1)
        if code != 200:
            warn(f"GET {base}/_wasql_install_check.php returned {code or 'no response'}")
            if text:
                debug(text[:600])
            return {}
        if text.lstrip().startswith("<?"):
            warn("Apache served the PHP source instead of running it - "
                 "the PHP module/handler is not active")
            return {}
        try:
            result = json.loads(text)
        except json.JSONDecodeError:
            warn("unexpected response from the check script:\n" + text[:400])
            return {}
    finally:
        if not DRY_RUN and check.exists():
            check.unlink(missing_ok=True)

    ok(f"PHP {result.get('php')} running under Apache ({result.get('sapi')})")
    exts = set(result.get("extensions", []))
    missing = [e for e in REQUIRED_EXTS if e.lower() not in exts]
    if missing:
        warn("REQUIRED PHP extensions missing: " + ", ".join(missing))
    else:
        ok("all required PHP extensions are loaded")
    soft = [e for e in RECOMMENDED_EXTS if e.lower() not in exts]
    if soft:
        info(f"optional extensions not loaded: {', '.join(soft)}")
    for path, w in (result.get("writable") or {}).items():
        if w is False:
            warn(f"not writable by the web server: {path}")
    db = result.get("db") or {}
    if db.get("ok"):
        ok(f"mysqli connected to `{s.db_name}` as {s.db_user}")
    else:
        warn(f"PHP could not reach the database: {db.get('error')}")
    return result


def install_sample_site(s: Settings, admin: MySQLAdmin) -> None:
    """Drive WaSQL's own setup wizard over HTTP so this stays hands-off."""
    if s.sample == "none":
        info("skipping sample site creation (--sample none)")
        return
    step(f"Creating the '{s.sample}' sample site")
    if DRY_RUN:
        info(f"{C.DIM}[dry-run] GET /?starttype={s.sample}{C.OFF}")
        return
    zip_path = s.wasql / "php" / "schema" / "templates" / f"{s.sample}.zip"
    if not zip_path.is_file():
        warn(f"{zip_path} not found; skipping (open http://localhost/ to pick "
             "a template by hand)")
        return
    r = admin.sql(f"SELECT COUNT(*) FROM information_schema.tables WHERE "
                  f"table_schema='{sql_quote(s.db_name)}' AND table_name='_users';")
    if r.good and re.search(r"\b1\b", r.out.splitlines()[-1] if r.out else ""):
        ok("database already initialised (_users exists) - wizard skipped")
        return
    base = f"http://localhost{'' if s.port == 80 else ':' + str(s.port)}"
    info("running the WaSQL setup wizard (this can take a minute)")
    code, text = http_get(f"{base}/?starttype={s.sample}", timeout=600)
    if code != 200:
        warn(f"setup wizard returned HTTP {code}; open {base}/ and click a "
             "template to finish")
        debug(text[:600])
        return
    if re.search(r"Site Created", text, re.I):
        ok(f"'{s.sample}' site created")
    else:
        warn("the wizard responded but did not confirm creation; open "
             f"{base}/ to check")
        debug(text[:800])
    r = admin.sql("SELECT COUNT(*) FROM `_pages`;", database=s.db_name)
    if r.good:
        info(f"_pages rows: {r.out.splitlines()[-1] if r.out else '?'}")


# ---------------------------------------------------------------------------
# summary
# ---------------------------------------------------------------------------

def summary(s: Settings, stack: Stack, admin: MySQLAdmin, checked: dict):
    base = f"http://localhost{'' if s.port == 80 else ':' + str(s.port)}"
    print(f"\n{C.BOLD}{'=' * 68}{C.OFF}")
    print(f"{C.BOLD}WaSQL local install summary{C.OFF}")
    print(f"{C.BOLD}{'=' * 68}{C.OFF}")
    print(f"  site            {base}/")
    print(f"  admin           {base}/php/admin.php   (login admin / admin)")
    print(f"  wasql dir       {s.wasql}")
    print(f"  document root   {s.docroot}")
    print(f"  apache          {stack.apache.binary or '?'}")
    if stack.apache.conf:
        print(f"  apache conf     {stack.apache.conf}")
    print(f"  php             {stack.php.binary or '?'}"
          f"{' (' + stack.php.version + ')' if stack.php.version else ''}")
    if stack.php.ini:
        print(f"  php.ini         {stack.php.ini}")
    print(f"  mysql client    {stack.mysql.client or '?'}")
    print(f"  database        {s.db_name}  (user {s.db_user} / {s.db_pass})")
    if s.mysql_root_pass:
        print(f"  mysql root      password set by this installer")
    print(f"  config.xml      {s.wasql / 'config.xml'}")
    print(f"  error log       {s.wasql / 'logs' / 'wasql_errors.log'}")
    if IS_LINUX:
        svc = stack.apache.service
        print(f"\n  restart apache  systemctl restart {svc}")
        print(f"  restart mysql   systemctl restart {stack.mysql.service}")
    elif IS_MAC:
        print("\n  restart apache  sudo brew services restart httpd")
        print("  restart mysql   brew services restart mysql")
    else:
        print(f"\n  restart apache  net stop {stack.apache.service} && "
              f"net start {stack.apache.service}")
        print(f"  restart mysql   net stop {stack.mysql.service} && "
              f"net start {stack.mysql.service}")
    if _WARNINGS:
        print(f"\n{C.YELLOW}{C.BOLD}{len(_WARNINGS)} warning(s):{C.OFF}")
        for w in _WARNINGS:
            print(f"  - {w.splitlines()[0]}")
    if IS_WIN:
        print(f"\n{C.DIM}  Note: the PHP directory was added to the machine "
              f"PATH; a reboot makes it visible to every process.{C.OFF}")
    healthy = bool(checked) and (checked.get("db") or {}).get("ok")
    if healthy and not _WARNINGS:
        print(f"\n{C.GREEN}{C.BOLD}Done - open {base}/ in a browser.{C.OFF}\n")
    elif healthy:
        print(f"\n{C.GREEN}Done with warnings - open {base}/ in a browser.{C.OFF}\n")
    else:
        print(f"\n{C.YELLOW}Finished, but verification did not fully pass. "
              f"Re-run with --check --verbose to dig in.{C.OFF}\n")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def build_stack(s: Settings) -> Stack:
    if IS_WIN:
        return WindowsStack(s)
    if IS_MAC:
        return MacStack(s)
    if IS_LINUX:
        return LinuxStack(s)
    die(f"unsupported platform: {sys.platform}")


def parse_args(argv: list[str]):
    p = argparse.ArgumentParser(
        prog="install_localhost.py",
        description="Install and configure Apache + PHP + MySQL for WaSQL on "
                    "localhost (Windows, Linux, macOS).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="examples:\n"
               "  python3 install_localhost.py                 # ask, then run\n"
               "  python3 install_localhost.py --yes            # all defaults\n"
               "  python3 install_localhost.py --skip-install    # configure only\n"
               "  python3 install_localhost.py --check           # verify only\n")
    p.add_argument("-y", "--yes", action="store_true",
                   help="accept every default, ask nothing")
    p.add_argument("--wasql", help="path to the WaSQL checkout "
                                   "(default: this script's directory)")
    p.add_argument("--docroot", help="Apache DocumentRoot (default: the WaSQL dir)")
    p.add_argument("--port", type=int, help=f"Apache port (default {DEFAULT_PORT})")
    p.add_argument("--db-name", help=f"WaSQL database (default {DEFAULT_DB_NAME})")
    p.add_argument("--db-user", help=f"WaSQL db user (default {DEFAULT_DB_USER})")
    p.add_argument("--db-pass", help=f"WaSQL db password (default {DEFAULT_DB_PASS})")
    p.add_argument("--mysql-root-pass", help="set/use this MySQL root password")
    p.add_argument("--sample", choices=SAMPLE_CHOICES,
                   help=f"sample site to install (default {DEFAULT_SAMPLE})")
    p.add_argument("--php-version", help="Windows only: PHP branch to fetch, e.g. 8.4")
    p.add_argument("--timezone", help="PHP date.timezone")
    p.add_argument("--skip-install", action="store_true",
                   help="do not install packages, only configure what is here")
    p.add_argument("--force-config", action="store_true",
                   help="overwrite an existing config.xml (a backup is kept)")
    p.add_argument("--strict-sql-mode", action="store_true",
                   help="leave MySQL sql_mode alone (default: relax it)")
    p.add_argument("--check", action="store_true",
                   help="only verify an existing install and exit")
    p.add_argument("--dry-run", action="store_true",
                   help="print what would happen; change nothing")
    p.add_argument("-v", "--verbose", action="store_true")
    return p.parse_args(argv)


def main(argv: list[str]) -> int:
    global VERBOSE, DRY_RUN
    args = parse_args(argv)
    VERBOSE = args.verbose
    DRY_RUN = args.dry_run
    _init_console()

    # --check and --dry-run only read; everything else needs root/admin
    if not DRY_RUN and not args.check:
        require_privileges(argv)

    s = gather_settings(args)
    stack = build_stack(s)

    step(f"Locating the existing stack ({stack.label})")
    stack.detect()
    info(f"apache : {stack.apache.binary or 'not found'}")
    info(f"php    : {stack.php.binary or 'not found'}"
         f"{' (' + stack.php.version + ')' if stack.php.version else ''}")
    info(f"php mod: {stack.php.apache_module or stack.php.fpm_service or 'not found'}")
    info(f"mysql  : {stack.mysql.client or 'not found'}")

    if args.check:
        admin = MySQLAdmin(stack.mysql.client, s.mysql_root_pass, allow_sudo=True) \
            if stack.mysql.client else None
        checked = verify(s, stack)
        summary(s, stack, admin, checked)
        return 0 if checked else 1

    if s.install_packages:
        stack.install()
    else:
        info("--skip-install: using what is already installed")

    step("Preparing WaSQL directories")
    wasql_filesystem(s, stack)

    step("Writing config.xml")
    wasql_config_xml(s)

    step("Configuring PHP")
    stack.php_write_ini()

    configure_apache(s, stack)

    if isinstance(stack, LinuxStack):
        stack.selinux_fixup()

    step("Starting MySQL")
    r = stack.mysql_start()
    if r.good:
        ok("MySQL is running")
    else:
        warn(f"MySQL may not be running: {r.text.splitlines()[:2]}")

    step("Creating the WaSQL database and user")
    if not stack.mysql.client:
        warn("no mysql client found; skipping database setup")
        admin = MySQLAdmin(Path("mysql"), s.mysql_root_pass, allow_sudo=True)
    else:
        admin = MySQLAdmin(stack.mysql.client, s.mysql_root_pass, allow_sudo=True)
        if setup_database(s, admin):
            tune_mysql(s, admin, stack)

    step("Starting Apache")
    if s.port != 80 and port_in_use(s.port):
        info(f"port {s.port} is already answering - it will be taken over/reused")
    r = stack.apache_restart()
    if r.good:
        ok("Apache restarted")
    else:
        warn("Apache did not start cleanly:\n" +
             "\n".join(r.text.splitlines()[-10:]))

    checked = verify(s, stack)
    if checked:
        install_sample_site(s, admin)

    summary(s, stack, admin, checked)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except KeyboardInterrupt:
        print()
        die("interrupted", 130)
